### PR TITLE
fix build after merge of outdated PR

### PR DESCRIPTION
**Pull request by thaJeztah**
this broke after e554ab558985b686c9c3427275a5e016aa1cdb76 (https://github.com/moby/moby/pull/39699), was merged but the PR was outdated.

```
[2019-08-28T00:27:12.031Z] builder/dockerfile/copy.go:566:29: too many arguments in call to system.MkdirAll
[2019-08-28T00:27:12.031Z] 	have (string, number, string)
[2019-08-28T00:27:12.031Z] 	want (string, os.FileMode)
```

### CODE REVIEW

**Comment by thaJeztah** [comment]
Wowza... they were working on some change in Jenkins, but erm.. that cause quite a bit of a queue taken up by the docker-compose repo

Screenshot 2019-08-28 at 03 36 51
Screenshot 2019-08-28 at 03 39 48

**Comment by thaJeztah** [comment]
OK; it's building again with this PR; https://ci.docker.com/public/job/moby/job/PR-39809/1/execution/node/217/log/

```
03:42:34  Building test suite binary /go/src/github.com/docker/docker/integration/build/test.main
03:45:25  Building test suite binary /go/src/github.com/docker/docker/integration/config/test.main
03:45:25  Building test suite binary /go/src/github.com/docker/docker/integration/container/test.main
03:45:35  Building test suite binary /go/src/github.com/docker/docker/integration/image/test.main
03:45:42  Building test suite binary /go/src/github.com/docker/docker/integration/network/test.main
03:45:49  Building test suite binary /go/src/github.com/docker/docker/integration/network/ipvlan/test.main
03:45:57  Building test suite binary /go/src/github.com/docker/docker/integration/network/macvlan/test.main
03:46:03  Building test suite binary /go/src/github.com/docker/docker/integration/plugin/test.main
03:46:04  Building test suite binary /go/src/github.com/docker/docker/integration/plugin/authz/test.main
03:46:12  Building test suite binary /go/src/github.com/docker/docker/integration/plugin/common/test.main
03:46:15  Building test suite binary /go/src/github.com/docker/docker/integration/plugin/graphdriver/test.main
03:46:22  Building test suite binary /go/src/github.com/docker/docker/integration/plugin/logging/test.main
03:46:30  Building test suite binary /go/src/github.com/docker/docker/integration/plugin/volumes/test.main
03:46:38  Building test suite binary /go/src/github.com/docker/docker/integration/secret/test.main
03:46:44  Building test suite binary /go/src/github.com/docker/docker/integration/service/test.main
03:46:53  Building test suite binary /go/src/github.com/docker/docker/integration/session/test.main
03:46:54  Building test suite binary /go/src/github.com/docker/docker/integration/system/test.main
03:47:01  Building test suite binary /go/src/github.com/docker/docker/integration/volume/test.main
03:47:05  ---> Making bundle: .integration-daemon-start (in /go/src/github.com/docker/docker/bundles/test-integration/1)
03:47:05  Using test binary docker
```

**Comment by thaJeztah** [comment]
@tiborvass @tonistiigi PTAL

**Review by tiborvass — APPROVED** [review]
