### PR TITLE
Switch from x/net/context -> context

### PR DESCRIPTION
**Pull request by kolyshkin**
Since Go 1.7, `context` is a standard package. Since Go 1.9, all `x/net/context` is a few aliases to types in `context`.

Many vendored packages still use x/net/context, so vendor entry remains for now.

The commit is generated by this ugly script (I'm bad at sed so had to use awk in between):

```bash
#!/bin/bash

for f in $(git ls-files \*.go | grep -v ^vendor/); do
	printf .
	sed -i 's|"golang.org/x/net/context"|"context"|' $f
# fix the position of "context" line
	goimports -w $f
# remove the empty line before "context"
	awk '/^$/ {e=1; next;}
		/^\t"context"$/ {e=0;}
		{if (e) {print ""; e=0}; print;}' < $f > $f.new && mv $f.new $f
# fix the position of "context" line again
	goimports -w $f
done
echo
```

Note that there is a "standard" way of doing this change -- by running the `go tool fix -r context`, what it does is the same as the `sed` above. In addition, I had to fix the `"context"` line placement which was tricky in case there are empty lines in the imports list (thus the two `goimports` with an awk in between.

### CODE REVIEW

**Comment by kolyshkin** [comment]
> We'll probably need something similar for swarmkit, containerd, libnetwork as well (assuming it works)

Looking into it...

> Looks like you need to (re-)vendor something

Oops, the sed regex was too greedy. Fixed.

**Comment by kolyshkin** [comment]
It looks like as long as Go >= 1.9 is used, we can mix `x/net/context` and `context` freely.

**Comment by kolyshkin** [comment]
Nice, it looks like the switch revealed a couple of bugs in the code:
```
15:44:42 pkg/ioutils/readers_test.go:83::error: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (vet)
15:44:42 daemon/cluster/swarm.go:507::error: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (vet)
```

**Comment by kolyshkin** [comment]
> FYI, you can do this migration with go tool fix -r context <paths> (using go1.10)

Just found that out myself. The problems with the above tool are:
1. It fixes stuff in vendor/ too.
2. It doesn't fix the placement of the `"context"` line in `imports` list in case there are empty lines in it.

**Comment by kolyshkin** [comment]
CI failure on experimental:
```
16:12:47 --- FAIL: TestCreateServiceConfigFileMode (12.36s)
16:12:47 	daemon.go:269: [d7e8cb005d1a9] waiting for daemon to start
16:12:47 	daemon.go:301: [d7e8cb005d1a9] daemon started
16:12:47 	create_test.go:295: timeout hit after 10s: task count at 1 waiting for 0
16:12:47 	daemon.go:259: [d7e8cb005d1a9] exiting daemon
```

Hmm, it does not look related but does not look like a flaky test either

**Comment by thaJeztah** [comment]
I think I just saw that one fail on another PR as well

**Comment by dnephin** [comment]
> The problems with the above tool are:


I guess it would need a `git reset HEAD vendor && goimports -w ./...`

**Comment by thaJeztah** [comment]
@kolyshkin needs  a rebase 😅, also perhaps it's good to keep the fixes in a separate PR

**Comment by kolyshkin** [comment]
> I guess it would need a git reset HEAD vendor && goimports -w ./...

Unfortunately not -- in case there is an empty line between "standard" and "prefixed" packages, it still won't have "context" in the line it should be, this is why I have to do `goimports -w` twice in my list, with an empty line removal in between.

**Comment by kolyshkin** [comment]
> @kolyshkin needs a rebase 

done

>  also perhaps it's good to keep the fixes in a separate PR

it was that way already

**Comment by kolyshkin** [comment]
> also perhaps it's good to keep the fixes in a separate PR

done (#36920), but this way CI here will fail as in https://github.com/moby/moby/pull/36904#issuecomment-382903562

**Comment by kolyshkin** [comment]
rebased again

**Review by cpuguy83 — APPROVED** [review]
If CI is happy I'm happy. LGTM!

**Review by AkihiroSuda — APPROVED** [review]

**Comment by cpuguy83** [comment]
```
06:28:53 daemon/cluster/swarm.go:507::error: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (vet)
06:28:53 pkg/ioutils/readers_test.go:83::error: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (vet)
```

**Comment by kolyshkin** [comment]
@cpuguy83 the fix for this is separated to https://github.com/moby/moby/pull/36920 as per request in https://github.com/moby/moby/pull/36904#issuecomment-383147633

**Comment by kolyshkin** [comment]
Rebased to master (with https://github.com/moby/moby/pull/36920 merged)

**Review by thaJeztah — APPROVED** [review]
LGTM!
