### PR TITLE
[25.0] vendor: google.golang.org/grpc v1.83.1

### PR DESCRIPTION
**Pull request by dperny**
- Related to: https://github.com/moby/moby/pull/53439 (master: grpc v1.83.1)
- Backport of: https://github.com/moby/moby/pull/47919 (master: `otel: remove deprecated usages of otelgrpc`)

## Summary

Bumps `google.golang.org/grpc` v1.80.0 -> v1.83.1 to fix
[CVE-2026-84304](https://www.cve.org/CVERecord?id=CVE-2026-84304) /
[GHSA-vp52-pcj8-j9qc](https://github.com/grpc/grpc-go/security/advisories/GHSA-vp52-pcj8-j9qc),
a heap-exhaustion denial of service.

`internal/transport/transport.go` stored each fragmented HTTP/2 DATA frame as its own
`recvMsg` in `recvBuffer`, so a peer sending millions of one-byte frames could consume
disproportionate heap while staying inside the connection and stream flow-control
windows. An unauthenticated remote peer could use concurrent multiplexed streams to
force a runtime panic or OOM. Everything up to and including v1.83.0 is affected; the
fix is grpc/grpc-go#9331, released in v1.83.1.

full diff: https://github.com/grpc/grpc-go/compare/v1.80.0...v1.83.1

## This needs a code change as well

`grpc` v1.83.1 requires `cloud.google.com/go/auth` v0.18.2, which requires
`otelgrpc` v0.61.0 — and **v0.61.0 removes the deprecated `UnaryClientInterceptor` and
`UnaryServerInterceptor` constructors**. (It keeps the `Stream*` ones.) That breaks
three call sites on this branch:

```
api/server/router/grpc/grpc.go:49:24              undefined: otelgrpc.UnaryServerInterceptor
daemon/daemon.go:975:38                           undefined: otelgrpc.UnaryClientInterceptor
libcontainerd/supervisor/remote_daemon.go:305:41  undefined: otelgrpc.UnaryClientInterceptor
```

These are the sites already carrying `//nolint:staticcheck // TODO(thaJeztah): ... see #47437`.
The first commit here is a clean `cherry-pick -x` of 49ca0d0d03 from #47919, which is the
migration master already made: the interceptor pairs become a single
`grpc.StatsHandler(tracing.ServerStatsHandler(...))` / `grpc.WithStatsHandler(tracing.ClientStatsHandler(...))`.

Worth noting for reviewers: that upstream commit also adds error logging to the unary
interceptor on the `/grpc` route, which is not related to the dependency bump. It is kept
here so the backport matches master verbatim rather than being a hand-edited variant —
happy to trim it if you would rather this branch stayed minimal.

The OTLP-loop guard is preserved. `tracing.ServerStatsHandler` applies buildkit's
`defaultStatsFilter`, which already excludes
`opentelemetry.proto.collector.trace.v1.TraceService/Export` (and `Health/Check`), so the
hand-rolled filter in `unaryInterceptor` is no longer needed for that purpose.

Both commits build independently — the migration compiles against the current
grpc v1.80.0, so the series is bisectable.

## Other version changes

`grpc` v1.83.1 raises the minimum version of several of its own dependencies, and
`hack/vendor.sh` bumps those along with it. **No module is added to or removed from the
vendor tree**; these are the only version changes:

| module | from | to |
| --- | --- | --- |
| `cloud.google.com/go` | v0.120.0 | v0.123.0 |
| `cloud.google.com/go/auth` | v0.15.0 | v0.18.2 |
| `cloud.google.com/go/logging` | v1.13.0 | v1.13.1 |
| `cloud.google.com/go/longrunning` | v0.6.6 | v0.8.0 |
| `github.com/googleapis/enterprise-certificate-proxy` | v0.3.6 | v0.3.11 |
| `github.com/googleapis/gax-go/v2` | v2.14.1 | v2.17.0 |
| `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc` | v0.60.0 | v0.61.0 |
| `go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp` | v0.60.0 | v0.61.0 |
| `go.opentelemetry.io/otel` (and `metric`, `sdk`, `trace`) | v1.43.0 | v1.44.0 |
| `golang.org/x/time` | v0.12.0 | v0.14.0 |
| `google.golang.org/api` | v0.228.0 | v0.264.0 |
| `google.golang.org/genproto` | `20250324211829` | `20260128011058` |
| `google.golang.org/genproto/googleapis/api` | `20260401024825` | `20260526163538` |
| `google.golang.org/genproto/googleapis/rpc` | `20260401024825` | `20260526163538` |

The diff is large (~46k lines) because `google.golang.org/api` and the
`cloud.google.com/go` modules are re-vendored in full, but the dependency surface is
unchanged.

## Release notes (optional)

```markdown changelog
- Fix a denial of service (CVE-2026-84304) where a remote peer sending large numbers of small HTTP/2 DATA frames could exhaust the daemon's memory.
```

## A picture of a cute animal (not mandatory but encouraged)

🦦

### CODE REVIEW

**Review by corhere — APPROVED** [review]

**Comment by corhere** [comment]
@dperny needs a re-vendor

**Comment by dperny** [comment]
Pushed a fix for the `validate (vendor)` failure, and added a commit.

The otelgrpc migration in the first commit replaces `grpc_middleware.ChainUnaryServer` / `ChainStreamServer` with grpc's own `ChainUnaryInterceptor` / `StreamInterceptor`, which removes the last use of `github.com/grpc-ecosystem/go-grpc-middleware` outside `vendor/` on this branch. I had computed the vendor state before applying the migration, so `vendor.mod` still declared a module nothing imported. `hack/vendor.sh` now drops it.

The series is:

```
830f512bb9  vendor: google.golang.org/grpc v1.83.1
f40d6c70c5  vendor: remove github.com/grpc-ecosystem/go-grpc-middleware
712b08e100  otel: remove deprecated usages of `otelgrpc`   (cherry-pick -x of 49ca0d0d03)
```

The removal is a separate commit rather than folded into the cherry-pick, so that commit keeps matching upstream verbatim — `49ca0d0d03` carried no vendor changes itself, since on master the module was still reachable from other code at the time.

One consequence worth flagging: **the cherry-pick commit on its own does not pass `validate-vendor`**; the drift is corrected in the very next commit. Happy to squash the removal into it if you would rather every commit be independently clean, at the cost of it no longer matching upstream byte for byte.

`hack/vendor.sh` now produces no drift at either of the two `vendor:` commits, `go build ./...` is clean, and `go mod verify` passes.

The remaining red jobs — `build`/`cross`/`smoke` on arm/v5, arm/v6 and s390x, and the integration suites — are the bookworm-LTS breakage you noted on #53619, not something from this branch. They fail identically on #53621, which contains no code change at all.

**Comment by corhere** [comment]
@dperny squash, please: each commit should be bisectable.

**Comment by dperny** [comment]
Squashed — the series is two commits now, and `hack/vendor.sh` produces no drift at either of them:

```
ff80d2a056  vendor: google.golang.org/grpc v1.83.1
0f25bc4246  otel: remove deprecated usages of `otelgrpc`
```

The `go-grpc-middleware` removal is folded into the first commit rather than following it, since that is what made the cherry-pick fail `validate-vendor` on its own. The commit keeps its `(cherry picked from commit 49ca0d0d03…)` line but is no longer byte-identical to upstream, and the message says so and why — upstream carried no vendor changes there because on master the module was still reachable from other code.

I kept the dependency bump separate from the code change rather than squashing all three into one; say the word if you would rather it were a single commit.

Verified at each commit: `hack/vendor.sh all` leaves the tree unchanged, and `go build ./...` is clean at the head.

**Review by corhere — APPROVED** [review]
