### PR TITLE
switch to moby/sys/{mount,mountinfo} part II

### PR DESCRIPTION
**Pull request by kolyshkin**
This PR finishes the replacement of the `pkg/mount` package with github.com/moby/sys/mount and github.com/moby/sys/mountinfo.

Step by step:
 - [x] Vendor in github.com/moby/sys
 - [x] make pkg/mount a shallow package
(the above is https://github.com/moby/moby/pull/40691; the below is this PR)
 - [x] really switch this repo to use moby/sys directly
 - [x] add deprecation notice to pkg/mount

The long-term plan is to remove `pkg/mount` entirely. This, of course, depends on its external users (I'm afraid we have a lot; I was going to get it from e.g. https://pkg.go.dev/github.com/docker/docker@v1.13.0/pkg/mount?tab=importedby but because it does not recognize moby's v17...v19 tags it's not possible, so it shows users of v.1.13.0. Filed https://github.com/golang/go/issues/37851)

### CODE REVIEW

**Comment by kolyshkin** [comment]
CI failures seem unrelated
> [2020-03-14T01:38:39.122Z] === Failed
> [2020-03-14T01:38:39.122Z] === FAIL: s390x.integration.network TestInspectNetwork (7.44s)
> [2020-03-14T01:38:39.122Z] 
> [2020-03-14T01:38:39.122Z] === FAIL: s390x.integration.network TestServiceWithDataPathPortInit (27.00s)
> [2020-03-14T01:38:39.122Z]     service_test.go:378: timeout hit after 15s: running task count at 0 waiting for 1 (total tasks: 4)
> [2020-03-14T01:38:39.122Z] 
> [2020-03-14T01:38:39.122Z] === FAIL: s390x.integration.network TestServiceWithDefaultAddressPoolInit (17.38s)
> [2020-03-14T01:38:39.122Z]     service_test.go:420: timeout hit after 15s: running task count at 0 waiting for 1 (total tasks: 4)

**Review by AkihiroSuda — APPROVED** [review]

File: pkg/mount/flags.go [hunk 1]
```diff
@@ -1,137 +1,34 @@
...
-// Parse fstab type mount options into mount() flags
-// and device specific data
-func parseOptions(options string) (int, string) {
-	var (
-		flag int
-		data []string
-	)
+//nolint:golint
+const (
+	RDONLY      = sysmount.RDONLY
```
Comment (thaJeztah) [inline pkg/mount/flags.go]: can you add `// Deprecated: ` comments after each?

Similar to what I did in https://github.com/moby/moby/commit/f572df7c22c1f48b9a2ddd51519797a5b6a2eda4#diff-e1546f0e7fe0b238191ff0cb82342936

File: pkg/mount/mount.go [hunk 2]
```diff
@@ -1,151 +1,20 @@
...
+// Package mount implements methods to perform mounts and unmounts,
+// and get information about existing mounts.
 //
-// Deprecated: use Mount instead.
-func ForceMount(device, target, mType, options string) error {
-	flag, data := parseOptions(options)
-	return mount(device, target, mType, uintptr(flag), data)
-}
+// Deprecated: this package is no longer maintained and will be removed.
+// Pplease switch to github.com/moby/sys/mount (for mounting) and/or
```
Comment (thaJeztah) [inline pkg/mount/mount.go]: Typo Pplease 

but I think we could skip the niceties and bring the message more direct;

    // Deprecated: this package is deprecated, use github.com/moby/sys/mount and github.com/moby/sys/mountinfo instead

File: pkg/mount/mountinfo.go [hunk 3]
```diff
@@ -1,40 +1,22 @@
...
-	// VfsOpts represents per super block options.
-	VfsOpts string
-}
+import (
+	"github.com/moby/sys/mountinfo"
+)
+
+//nolint:golint
+type (
+	FilterFunc = mountinfo.FilterFunc
```
Comment (thaJeztah) [inline pkg/mount/mountinfo.go]: Same as the other PR; I think we can probably collect all these in a single "deprecated.go" file

**Review by thaJeztah — CHANGES_REQUESTED** [review]

File: pkg/mount/flags.go (hunk 1 above)
Comment (kolyshkin) [reply pkg/mount/flags.go]: The whole package is deprecated (see the last commit). From what I understood from https://github.com/golang/go/wiki/Deprecated, it should be sufficient.

I guess you were reviewing the second commit. At this point, this package is still used as marking it deprecated will result in validation failure. So, I only marked it as deprecated once I switched the codebase to use moby/sys

File: pkg/mount/mount.go (hunk 2 above)
Comment (kolyshkin) [reply pkg/mount/mount.go]: I was trying to not use the word "deprecated" twice, since it appears in documentation as is.

Thanks, fixed

File: pkg/mount/deprecated.go [hunk 4]
```diff
@@ -39,15 +44,18 @@ const (
 	STRICTATIME = sysmount.STRICTATIME
 )
 
+// Deprecated: use github.com/moby/sys/mount instead.
 //nolint:golint
```
Comment (thaJeztah) [inline pkg/mount/deprecated.go]: Is the linter complaining without the `//nolint` comments? The downside of these is that they are only taken into account by our custom linters (such as golang-ci-lint), but, e.g. ignored by `golang.org/x/lint` itself, and thus would show up on https://goreportcard.com/report/github.com/containerd/containerd#golint

Comment (kolyshkin) [reply pkg/mount/deprecated.go]: nolint:golint was added to get rid of "not documented" warnings. Maybe when "Deprecated" documentation is added, this is no longer needed. Let me try.

Comment (kolyshkin) [reply pkg/mount/deprecated.go]: Let's see if removing `golint:nolint` works (if not, I'll revert)

Comment (kolyshkin) [reply pkg/mount/deprecated.go]:
```
[2020-03-19T18:27:31.851Z] // Deprecated: use github.com/moby/sys/mount instead.
[2020-03-19T18:27:31.851Z] ^
[2020-03-19T18:27:31.851Z] pkg/mount/deprecated.go:48:1: comment on exported type FilterFunc should be of the form "FilterFunc ..." (with optional leading article) (golint)
[2020-03-19T18:27:31.851Z] // Deprecated: use github.com/moby/sys/mountinfo instead.
[2020-03-19T18:27:31.851Z] ^
```

Nope, `golint` still complains, reverting the last change back

**Comment by kolyshkin** [comment]
updated to latest moby/sys

**Comment by cpuguy83** [comment]
```
[2020-03-19T19:38:46.083Z] 

[2020-03-19T19:38:46.083Z] ---> Making bundle: cross (in bundles/cross)

[2020-03-19T19:38:46.083Z] Cross building: bundles/cross/linux/amd64

[2020-03-19T19:38:46.083Z] Building: bundles/cross/linux/amd64/dockerd-dev

[2020-03-19T19:38:46.083Z] GOOS="linux" GOARCH="amd64" GOARM=""

[2020-03-19T19:40:07.493Z] Created binary: bundles/cross/linux/amd64/dockerd-dev

[2020-03-19T19:40:07.493Z] Copying nested executables into bundles/cross/linux/amd64

[2020-03-19T19:40:07.493Z] Cross building: bundles/cross/windows/amd64

[2020-03-19T19:40:07.493Z] Building: bundles/cross/windows/amd64/dockerd-dev.exe

[2020-03-19T19:40:07.493Z] GOOS="windows" GOARCH="amd64" GOARM=""

[2020-03-19T19:40:25.565Z] # github.com/docker/docker/vendor/github.com/moby/sys/mountinfo

[2020-03-19T19:40:25.565Z] vendor/github.com/moby/sys/mountinfo/mountinfo.go:16:9: undefined: parseInfoFile
```

**Comment by kolyshkin** [comment]
Oh shoot, this is caused by https://github.com/moby/sys/pull/6. Fixed by 

Eventually, we need to revert https://github.com/moby/moby/pull/21386, or somehow deprecate windows altogether.

**Comment by kolyshkin** [comment]
revendored newer moby/sys to fix windows build

**Review by cpuguy83 — APPROVED** [review]
LGTM

File: pkg/mount/mountinfo.go (hunk 3 above)
Comment (kolyshkin) [reply pkg/mount/mountinfo.go]: done

**Comment by kolyshkin** [comment]
Is there anything else that should be done here? It looks like ready to be merged from where i stand.

**Comment by thaJeztah** [comment]
Looks like golint still expects some godoc comments to be well-formed

```bash
go get -u golang.org/x/lint/golint
golint pkg/mount/...
pkg/mount/deprecated.go:47:1: comment on exported var MergeTmpfsOptions should be of the form "MergeTmpfsOptions ..."
pkg/mount/deprecated.go:51:1: comment on exported type FilterFunc should be of the form "FilterFunc ..." (with optional leading article)
pkg/mount/deprecated.go:51:1: comment on exported type Info should be of the form "Info ..." (with optional leading article)
```

**Comment by kolyshkin** [comment]
Added a separate commit to shut up a standalone-running `golint`.

**Review by thaJeztah — APPROVED** [review]
LGTM

perhaps the `//nolint` comments are not even needed anymore now

File: vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go [hunk 5]
```diff
@@ -1,4 +1,6 @@
-package mount // import "github.com/docker/docker/pkg/mount"
+// +build go1.13
```
Comment (tao12345666333) [inline vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go:1]: **Hello, I wonder if the build condition here has a special meaning?**

----
```
#37 0.675 Removing /build/bundles/
 #37 0.677 
 #37 0.684 ---> Making bundle: binary (in /build/bundles/binary)
 #37 0.821 Building: /build/bundles/binary-daemon/dockerd-0.0.0-20200404132736-92768b3296
 #37 0.823 GOOS="" GOARCH="" GOARM=""
 #37 33.99 # github.com/docker/docker/vendor/github.com/moby/sys/mountinfo
 #37 33.99 vendor/github.com/moby/sys/mountinfo/mountinfo.go:8:9: undefined: parseMountTable
 #37 33.99 vendor/github.com/moby/sys/mountinfo/mountinfo.go:16:9: undefined: parseInfoFile
 #37 ERROR: executor failed running [/bin/sh -c hack/make.sh binary]: runc did not terminate sucessfully
 ------
  > [build-binary 1/1] RUN --mount=type=cache,target=/root/.cache/go-build     --mount=type=bind,target=/go/src/github.com/docker/docker         hack/make.sh binary:
 ------
 failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: executor failed running [/bin/sh -c hack/make.sh binary]: runc did not terminate sucessfully
 make[2]: *** [Makefile:188: binary] Error 1
 make[2]: Leaving directory '/builds/[MASKED]/docker-ce-packaging/docker-ce/components/engine'
 make[1]: *** [Makefile:73: static-engine] Error 2
 make[1]: Leaving directory '/builds/[MASKED]/docker-ce-packaging/static'
 make: *** [Makefile:35: static] Error 2
```

I used GitLab CI for nightly build, but the recent task failed, and the above error message was found in the log.
After checking, I found that it was caused by the build condition here. (the build job using golang 1.12)

Comment (thaJeztah) [reply vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go:1]: Yes, this package requires Go 1.12 or up

Comment (tao12345666333) [reply vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go:1]: Thanks for your reply.
Go 1.12 or up? Should we change the  build condition?

Comment (thaJeztah) [reply vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go:1]: oh, sorry, wanted to type 1.13, and mis-typed 😂

Comment (tao12345666333) [reply vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go:1]: I have updated my build job to use 1.13 and it works fine. 

By the way, I want to ask, what is the reason why it needs 1.13? I checked the code and did not see the features that must be supported in 1.13, I don’t know if I missed something. Thanks!
