### PR TITLE
Fix docker stats parsing with large amount of interrupts

### LINKED ISSUE #49709: Docker stats doesn't work on 128 CPUs core system (error scanning '/proc/stat' file: bufio.Scanner: token too long")
### Description

We are unable to get stats from docker containers on ARM server with 128 CPU cores... The stats just shows zero values and /var/log/messages is spammed with this error message:

```
CONTAINER ID   NAME      CPU %     MEM USAGE / LIMIT   MEM %     NET I/O   BLOCK I/O   PIDS
75a2d37961f0   mysql1    0.00%     0B / 0B             0.00%     0B / 0B   0B / 0B     0
4da2f013161e   apache1   0.00%     0B / 0B             0.00%     0B / 0B   0B / 0B     0
```

```
Mar 28 11:40:36 localhost dockerd[2820]: time="2025-03-28T11:40:36.493046461+01:00" level=error msg="collecting stats for container /apache1: error scanning '/proc/stat' file: bufio.Scanner: token too long"
Mar 28 11:40:37 localhost dockerd[2820]: time="2025-03-28T11:40:37.495361805+01:00" level=error msg="collecting stats for container /mysql1: error scanning '/proc/stat' file: bufio.Scanner: token too long"
Mar 28 11:40:37 localhost dockerd[2820]: time="2025-03-28T11:40:37.497097407+01:00" level=error msg="collecting stats for container /apache1: error scanning '/proc/stat' file: bufio.Scanner: token too long"
Mar 28 11:40:38 localhost dockerd[2820]: time="2025-03-28T11:40:38.499816392+01:00" level=error msg="collecting stats for container /mysql1: error scanning '/proc/stat' file: bufio.Scanner: token too long"
Mar 28 11:40:38 localhost dockerd[2820]: time="2025-03-28T11:40:38.501417114+01:00" level=error msg="collecting stats for container /apache1: error scanning '/proc/stat' file: bufio.Scanner: token too long"
```

### Reproduce

Run any container on 128 CPU core system and check `docker stats`.

### Expected behavior

_No response_

### docker version

```bash
Client: Docker Engine - Community
 Version:           28.0.4
 API version:       1.48
 Go version:        go1.23.7
 Git commit:        b8034c0
 Built:             Tue Mar 25 15:10:30 2025
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.4
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.7
  Git commit:       6430e49
  Built:            Tue Mar 25 15:08:58 2025
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.26
  GitCommit:        753481ec61c7c8955a23d6ff7bc8e4daed455734
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 10
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 753481ec61c7c8955a23d6ff7bc8e4daed455734
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.14.0-503.33.1.el9_5.aarch64+64k
 Operating System: Rocky Linux 9.5 (Blue Onyx)
 OSType: linux
 Architecture: aarch64
 CPUs: 128
 Total Memory: 126.4GiB
 Name: localhost.localdomain
 ID: 75fc5d8d-e34f-458a-b3da-7ad00033e73c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by Shaggy84675**
Fixes #49709

**- What I did**
I've fixed a bug where `docker stats` was unable to collect stats on a machine with large amount of CPU cores and interrupts.

**- How I did**
I've changed scanner for reader to allow larger lines parsing (default 64kB scanner buffer) from /proc/stat. Scanner has of course option to increase the internal buffer size, but we wanted to avoid increasing the buffer and wasting memory just for a lines that are discarded anyway.

Another issue was if scanner threw an error, there's no way how to read at least the part that fits into the buffer, so it wasn't possisble to determine where the error exactly happened.

ReadLine function has a flag isPrefix that is set to true if the line is longer and doesn't fit into internal buffer. Based on that we can skip further processing.

**- How to verify it**
On a machine with large amount of interrupts (where the line exceeds 64kB in /proc/stat) run command `docker stats`.

```markdown changelog
Fix `docker stats` not working properly on machines with high CPU core count
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by vvoland — COMMENTED** [review]
Thanks!

I left some comments.

Also, could you please add unit tests that test this function against the example file contents we provided?

https://github.com/moby/moby/issues/49709#issuecomment-2761517638
https://github.com/moby/moby/issues/49709#issuecomment-2765716048

File: daemon/stats_unix.go [hunk 1]
```diff
@@ -351,10 +354,9 @@ func getSystemCPUUsage() (cpuUsage uint64, cpuNum uint32, _ error) {
 		if '0' <= line[3] && line[3] <= '9' {
 			cpuNum++
 		}
-	}
-
-	if err := scanner.Err(); err != nil {
-		return 0, 0, fmt.Errorf("error scanning '/proc/stat' file: %w", err)
+		if err != nil {
+			return 0, 0, fmt.Errorf("error scanning '/proc/stat' file: %w", err)
+		}
```
[the remark this answers is not in the document]
Comment (Shaggy84675) [reply daemon/stats_unix.go]: I've moved error handling right after line reading to skip further processing if something happens

File: daemon/stats_unix.go [hunk 2]
```diff
@@ -326,10 +326,13 @@ func getSystemCPUUsage() (cpuUsage uint64, cpuNum uint32, _ error) {
 	}
 	defer f.Close()
 
-	scanner := bufio.NewScanner(f)
-	for scanner.Scan() {
-		line := scanner.Text()
-		if len(line) < 4 || line[:3] != "cpu" {
+	rdr := bufio.NewReader(f)
```
[the remark this answers is not in the document]
Comment (Shaggy84675) [reply daemon/stats_unix.go]: Changed!

File: daemon/stats_unix.go [hunk 3]
```diff
@@ -326,10 +326,13 @@ func getSystemCPUUsage() (cpuUsage uint64, cpuNum uint32, _ error) {
...
+
+	for {
+		data, isPrefix, err := rdr.ReadLine()
```
[the remark this answers is not in the document]
Comment (Shaggy84675) [reply daemon/stats_unix.go]: > That's its name in https://pkg.go.dev/bufio#Reader.ReadLine
> 
> But, it'll be set for each partial read - then not-set on the final read of the long line. The data from that final read needs to be discarded too.
> 
> It'd be best to discard long lines before converting the bytes to a string, there's no need to check whether a line begins with "cpu" if the line's too long.

Good catch! I've separated the condition into two and skipping any further processing if partial read is true. The only trouble happens a bit with the last read... Didn't know it works this way.

Maybe it is alright it's converted into string and then discarded in the other condition that checks for cpu string? Since it's only one line with small size. Otherwise I'd have to probably add some kind of helper variable or nested loop that'd add more complexity.

[the remark this answers is not in the document]
Comment (robmry) [reply daemon/stats_unix.go]: Oh, I'm sorry - I completely misread it, and missed the assumption that cpu lines are first in the file. Thank you for moving the `string(data)`, I think that's slightly better - but not the issue I first thought! So, I think it can just be:

```go

// Assume all cpu* records are at the start of the file, like glibc:
// https://github.com/bminor/glibc/blob/5d00c201b9a2da768a79ea8d5311f257871c0b43/sysdeps/unix/sysv/linux/getsysstats.c#L108-L135
if isPartial || len(data) < 4 {
	break
}
line := string(data)
if line[:3] != "cpu" {
	break
}
```

(Please do squash the commits though.)

[the remark this answers is not in the document]
Comment (Shaggy84675) [reply daemon/stats_unix.go]: Thank you, fixed!

I think I've messed up squashing the commits.

**Comment by Shaggy84675** [comment]
> Thanks!
> 
> I left some comments.
> 
> Also, could you please add unit tests that test this function against the example file contents we provided?
> 
> [#49709 (comment)](https://github.com/moby/moby/issues/49709#issuecomment-2761517638) [#49709 (comment)](https://github.com/moby/moby/issues/49709#issuecomment-2765716048)

I've added the unit test. Please let me know if any improvements are needed.

I was also thinking if we should add more unit tests if the /proc/stat structure is different. But then I thought that may never happens i guess?

**Review by robmry — APPROVED** [review]
LGTM - thank you!

**Comment by robmry** [comment]
> I was also thinking if we should add more unit tests if the /proc/stat structure is different. But then I thought that may never happens i guess?

It wouldn't do any harm to test the error paths - but as it is, the change is already an improvement.

**Comment by robmry** [comment]
(Rebased to sort out the validate-vendor test.)

**Comment by robmry** [comment]
Oh, for the Windows unit tests, `daemon\stats_unix_test.go` needs `//go:build !windows` at the top of the file ...

```
daemon\stats_unix_test.go:16:18: undefined: procStatPath
daemon\stats_unix_test.go:17:2: undefined: procStatPath
daemon\stats_unix_test.go:18:17: undefined: procStatPath
```

**Review by vvoland — CHANGES_REQUESTED** [review]

File: daemon/stats_unix.go [hunk 4]
```diff
@@ -320,17 +322,28 @@ const (
 // provided. See `man 5 proc` for details on specific field
 // information.
 func getSystemCPUUsage() (cpuUsage uint64, cpuNum uint32, _ error) {
-	f, err := os.Open("/proc/stat")
+	f, err := os.Open(procStatPath)
```
Comment (vvoland) [inline daemon/stats_unix.go:325]: We could split this into two functions:

```go
func getSystemCPUUsage() (cpuUsage uint64, cpuNum uint32, _ error) {
	f, err := os.Open("/proc/stat")
	if err != nil {
		return 0, 0, err
	}
	defer f.Close()

    return readSystemCPUUsage(f)
}
```

```go
func readSystemCPUUsage(r io.Reader) (cpuUsage uint64, cpuNum uint32, _ error) {
    rdr := bufio.NewReaderSize(r, 1024)
    ...
}
```

File: daemon/stats_unix_test.go [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+)
+
+func TestGetSystemCPUUsageParsing(t *testing.T) {
+	dummyFilePath := filepath.Join("testdata", "stat")
+	expectedCpuUsage := uint64(65647090000000)
+	expectedCpuNum := uint32(128)
+
+	origStatPath := procStatPath
+	procStatPath = dummyFilePath
+	defer func() { procStatPath = origStatPath }()
```
Comment (vvoland) [inline daemon/stats_unix_test.go:18]: This way we can avoid replacing the file path and inline the testdata in the test:
```suggestion
	input := strings.NewReader(```
<stat content>
```)
```

File: daemon/stats_unix_test.go [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+
+	_, err := os.Stat(dummyFilePath)
+	assert.NilError(t, err)
+
+	cpuUsage, cpuNum, err := getSystemCPUUsage()
```
Comment (vvoland) [inline daemon/stats_unix_test.go:23]: And then test the function that allows passing the file content directly:
```suggestion
	cpuUsage, cpuNum, err := readSystemCPUUsage(input)
```

File: daemon/stats_unix_test.go [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+
+	assert.Equal(t, cpuUsage, expectedCpuUsage)
+	assert.Equal(t, cpuNum, expectedCpuNum)
```
Comment (vvoland) [inline daemon/stats_unix_test.go:26]: We can inline `expectedCpuUsage` and `expectedCpuNum` and use `cmp` assertions:

```suggestion
	assert.Check(t, is.Equal(cpuUsage, uint64(65647090000000)))
	assert.Check(t, is.Equal(cpuNum, uint32(128)))
```

**Review by vvoland — COMMENTED** [review]
And a couple of non-blocking suggestions 😄 

Not really blockers though, so can be left for a follow up.

**Comment by Shaggy84675** [comment]
> Oh, for the Windows unit tests, `daemon\stats_unix_test.go` needs `//go:build !windows` at the top of the file ...
> 
> ```
> daemon\stats_unix_test.go:16:18: undefined: procStatPath
> daemon\stats_unix_test.go:17:2: undefined: procStatPath
> daemon\stats_unix_test.go:18:17: undefined: procStatPath
> ```

@robmry @vvoland fixed. I think I've messed up your previous rebase, so you might need to do it again... I'm still fighting with it a bit sometimes 🙈

**Comment by robmry** [comment]
We can ignore the failed unit tests - `TestEndpointStore` is fixed by https://github.com/moby/moby/pull/49764

**Review by robmry — APPROVED** [review]

**Review by vvoland — APPROVED** [review]
Thanks!
