### PR TITLE
daemon: remove getNetworkID() helper

### PR DESCRIPTION
**Pull request by akerouanton**
**- What I did**

- Related to https://github.com/moby/moby/pull/46251

This helper was originally introduced in commit cafed80 to address an issue related to duplicated network names. As we don't allow such duplicates anymore, this helper can be removed.

### CODE REVIEW

**Comment by akerouanton** [comment]
cc @robmry

**Comment by thaJeztah** [comment]
Looks like build is failing;

```
52.99 daemon/container_operations.go:235:9: v declared and not used
52.99 daemon/container_operations.go:297:12: v declared and not used
52.99 daemon/container_operations.go:364:37: undefined: id
52.99 daemon/container_operations.go:365:45: undefined: id
52.99 daemon/container_operations.go:375:54: undefined: id
52.99 daemon/container_operations.go:381:31: undefined: id
52.99 daemon/container_operations.go:384:52: undefined: id
```

File: daemon/container_operations.go [hunk 1]
```diff
@@ -1140,15 +1138,6 @@ func (daemon *Daemon) DeactivateContainerServiceBinding(containerName string) er
 	return sb.DisableService()
 }
 
-func getNetworkID(name string, endpointSettings *networktypes.EndpointSettings) string {
-	// We only want to prefer NetworkID for user defined networks.
-	// For systems like bridge, none, etc. the name is preferred (otherwise restart may cause issues)
```
Comment (thaJeztah) [inline daemon/container_operations.go:1145]: Do the built-in network have a stable ID? (curious if they are re-created at restart, and if that was related as well)

Comment (akerouanton) [reply daemon/container_operations.go:1145]: Built-in networks are recreated if no containers are attached to them. Thus, they don't have a stable ID but that wasn't an issue here since the networks weren't recreated in that case.

Comment (thaJeztah) [reply daemon/container_operations.go:1145]: Right, so if there's an existing container (either _created_ or _running_) that's attached, the network won't be re-created, so the ID is stable, correct?

Is this code-path hit by Swarm, or not hit? (Just making sure, ISTR some subtle things with swarm pinning to an ID, and that ID of course being different between nodes or dynamically deployed, and IDs could not be used for that reason).
