### PR TITLE
Bump prometheus/client_golang and dependencies v1.3.0

### LINKED ISSUE #12: No longer builds against Prom master
Getting
```
../../docker/go-metrics/timer.go:39: cannot use lt.m.WithLabelValues(labels...) (type prometheus.Observer) as type prometheus.Histogram in field value:
	prometheus.Observer does not implement prometheus.Histogram (missing Collect method)
```

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] based on / depends on https://github.com/moby/moby/pull/40370

Updates prometheus to v1.3.0; given that this dependency wasn't updated for a while, doing so in some steps;

### vendor: bump prometheus/client_model v0.1.0

full diff: https://github.com/prometheus/client_model/compare/6f3806018612930941127f2a7c6c453ba2c527d2...v0.1.0

- prometheus/client_model#22 add `go_package`, regenerate Go binding file
- prometheus/client_model#31 Support Go Modules
- prometheus/client_model#38 Remove all languages but Go and add a deprecation note

### vendor: bump prometheus/common v0.7.0

full diff: https://github.com/prometheus/common/compare/7600349dcfe1abd18d72d3a1770870d9800a7801...v0.7.0

### vendor: bump prometheus/procfs v0.0.8

full diff: https://github.com/prometheus/procfs/compare/7d6f385de8bea29190f15ba9931442a0eaef9af7...v0.0.8

### vendor: bump prometheus/client_golang v0.9.4, docker/go-metrics v0.0.1

bump docker/go-metrics v0.0.1:

full diff: https://github.com/docker/go-metrics/compare/d466d4f6fd960e01820085bd7e1a24426ee7ef18...v0.0.1

- docker/go-metrics#16 fix the compilation error against prometheus/client-golang master
- fixes docker/go-metrics#12 No longer builds against Prom master
- docker/go-metrics#18 metrics: address compile error correctly
- fixes docker/go-metrics#12 No longer builds against Prom master
- docker/go-metrics#15 Add functions that instruments http handler using promhttp
- docker/go-metrics#20 Rename LICENSE.code → LICENSE
- docker/go-metrics#22 Support Go Modules

bump prometheus/client_golang v0.9.4:

full diff: https://github.com/prometheus/client_golang/compare/c5b7fccd204277076155f10851dad72b76a49317...v0.9.4

version v0.9.0 is the minimum required version to work with go-metrics v0.0.1,
as it depends on `prometheus.Observer`:

vendor/github.com/docker/go-metrics/timer.go:39:4: undefined: prometheus.Observer

### vendor: bump prometheus/client_golang v1.1.0

full diff: https://github.com/prometheus/client_golang/compare/v0.9.4...v1.1.0

Using v1.1.0, because version v1.2.0 and up use versioned import paths for the
github.com/cespare/xxhash/v2 dependency (prometheus/client_golang#657), which
causes vendoring with vndr to break due to the v2 in the import-path.

### vendor: bump prometheus/client_golang v1.3.0

full diff: https://github.com/prometheus/client_golang/compare/v1.1.0...v1.3.0

This requires LK4D/vndr v0.1.0 or newer for vendoring; also adds a new
dependency: github.com/cespare/xxhash

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Comment by thaJeztah** [comment]
oh, let me rebase this one to get rid of the commits from https://github.com/moby/moby/pull/40370 (otherwise it's confusing which PR introduced those)

**Comment by thaJeztah** [comment]
rebased: moved it to `status/4-merge`
