### ISSUE TITLE
Files randomly missing in volume mount from Windows host to Windows container after Windows 10 2004

### ISSUE THREAD

**Issue by KHeresy** [moby/moby#41388]
I had report this issue in Docker, but they tell me I should report here.
- https://github.com/docker/for-win/issues/8093

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 33C611F4-BE15-4CED-A58A-588F8739013F/20200817005404

### Expected behavior

I use Windows container with Visual Studio to build my project in CI/CD stage.

The Docker command like:
```
docker run -v S:\code\prject:c:\code --isolation process --rm MyBuilderImageName msbuild /nowarn:C4005,C4018,C4101,C4244,C4267,C4305,LNK4099 /v:minimal /m /p:Configuration=Release c:\code
```

This works fine before I upgrade Windows 10 to ver.2004.

After I upgrade to Windows 10 2004 (both host OS and Docker image), files may randomly missing when compile.

The missed file may different each time, and sometime it can run successfully without missing files.

### Actual behavior

Project build failed because file missing.

Error message may like:

```
c:\code\external\include\boost\config\abi_prefix.hpp(19,12): fatal error C1083: Cannot open include file: 'boost/config/abi/msvc_prefix.hpp': No such file or directory (compiling source file voxel.cpp) [c:\code\src\render\render.vcxproj]
```

It may build successfully without missing file, or missing another file if I try again.

### Information
  - Is it reproducible?
    - Randomly happen, but high frequency 
  - Did the problem appear with an update?
    - After upgrade Windows to 2004
  - Windows Version: Windows 10 2004 19041.450
  - Docker Desktop Version: 2.3.4.0 (Edge)
  - Docker Desktop Version: 2.3.0.4 (Stable)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, run in standalone Windows PC
  - Maybe the same issue as #5959 (Linux container)?

### Steps to reproduce the behavior

Dockerfile:
```
# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-2004

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Download the Build Tools 2019 bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
ADD https://aka.ms/vs/16/release/channel C:\TEMP\VisualStudio.chman

# Install Build Tools excluding workloads and components with known issues.
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --channelUri C:\TEMP\VisualStudio.chman `
    --installChannelUri C:\TEMP\VisualStudio.chman `
    --installPath C:\BuildTools `
    --add Microsoft.VisualStudio.Workload.VCTools `
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
    --add Microsoft.VisualStudio.Component.VC.ATLMFC `
    --add Microsoft.VisualStudio.Component.Windows10SDK.18362

# clean download files
RUN del C:\TEMP\* /q

# Start developer command prompt with any other commands specified.
ENTRYPOINT c:\BuildTools\VC\Auxiliary\Build\vcvars64.bat && 
```

**Comment by thaJeztah** [comment]
Is this the actual command you ran? I suspect there's a typo in that path (`prject` instead of `project`)

```
-v S:\code\prject:c:\code
```

```
c:\code\external\include\boost\config\abi_prefix.hpp(19,12): fatal error C1083: Cannot open include file: 'boost/config/abi/msvc_prefix.hpp': No such file or directory (compiling source file voxel.cpp) [c:\code\src\render\render.vcxproj]
```

Have you verified if the file is really missing, or if something else triggered the error? If you run the container interactively and check the files; is it missing?

Other things that stood out in these specific error;

- `boost/config/abi/msvc_prefix.hpp` uses slashes, not backslashes (perhaps expected, but curious)
- `boost/config/abi/msvc_prefix.hpp` looks like a relative path; if correct, what is it relative to?

**Comment by KHeresy** [comment]
Sorry, that is a typo.

I had confirmed the file is actually there.
I had also checked if the file is exist by interaction mode.

The missed file is not always the same file, compiler may report missing other files.

It may compile successfully when I try the same command next time. (without change any thing)

Other things:
- Slashes and backslashes in path make no differences in MSVC.
- The relationship of include path is defined in Visual C++ project.

I am sure the project can be compile successfully without Docker.

I compile the same project with the same setting, command in Docker without problem before I upgrade to Windows 10 2004.
This problem happens after I upgrade Windows 10 to version 2004.

**Comment by thaJeztah** [comment]
Sounds like a regression in Windows; the `S:\` drive is a regular, local drive?


ping @kevpar @jstarks ptal

**Comment by KHeresy** [comment]
Yes, it is a local SSD for reduce building time.

**Comment by KHeresy** [comment]
It looks that the issue not happen again after recently Windows / Docker update.
