### PR TITLE
pkg/mount: fix compile failure on Windows (move linux-only stubs0

### PR DESCRIPTION
**Pull request by thaJeztah**
Fixes the compile failure introduced in https://github.com/moby/moby/pull/41458, but somehow didn't cause Windows CI to report a failure 😞  https://github.com/moby/moby/pull/41458#issuecomment-722306672

For reference: I didn't look too closely if we're now stubbing all functions that were previously available on Windows; we're planning on removing these stubs altogether, and most of these should not be called on Windows (as they were non-functional or produced an error)

### CODE REVIEW

**Comment by thaJeztah** [comment]
@cpuguy83 @AkihiroSuda @TBBle ptal

**Comment by TBBle** [comment]
I have almost the same change sitting here, except I moved the non-Windows things into a _deprecated_unix.go_ to match the `sysmount` package they wrap.

Anyway, this LGTM, assuming CI passes now. I'm still looking into _why_ the failing unit tests didn't fail the pipeline...

Oops, another one to fix:
```
[2020-11-05T11:58:49.159Z] pkg\system\rm_test.go:62:12: undefined: mount.Mount
```

**Comment by thaJeztah** [comment]
> I have almost the same change sitting here, except I moved the non-Windows things into a deprecated_unix.go to match the sysmount package they wrap.

If you have a branch with those changes; feel free to push as a PR, and I'll close this one 👍 

> Oops, another one to fix:

Ah boo! My IDE didn't show up that one 😞

**Comment by thaJeztah** [comment]
(these stubs are mostly to provide a slightly smoother transition for users to switch to the new location, and we don't plan to continue maintaining them after 20.10, as mentioned)

**Comment by TBBle** [comment]
I don't have those changes pushed in a PR yet (I just did them locally while waiting for Jenkins), since I'm trying to validate my "fix the false-pass" changes first. But I'm happy to carry that through, and fix the other failure too. Currently in #41636 but I would break out the CI/test fixes separately from that PR once I know they work.

**Comment by TBBle** [comment]
I went ahead and pushed a PR to fix this, and the false-passes, in #41636

**Comment by thaJeztah** [comment]
Would it be ok to move the last two commits to a separate? Think we should be able to move faster to keep the PR focussed on a single fix

/me ducks

**Comment by TBBle** [comment]
Sorry, I linked the wrong PR. I meant #41638, which is just the CI fixes.

**Comment by thaJeztah** [comment]
oh, thanks!

**Comment by thaJeztah** [comment]
closing in favour of https://github.com/moby/moby/pull/41638
