### PR TITLE
Jenkinsfile: fix invalid expression in bundles script

### PR DESCRIPTION
**Pull request by thaJeztah**
This was introduced in a76ff632a4a833851ef36726c9e9bfb5e7dbed39 (https://github.com/moby/moby/pull/39790):

    + find bundles -path */root/*overlay2 -prune -o -type f ( -o -name *.log -o -name *.prof ) -print
    find: invalid expression; you have used a binary operator '-o' with nothing before it.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tiborvass @tianon @kolyshkin PTAL this was my mistake, looks like I screwed up in a rebase

**Review by tiborvass — APPROVED** [review]

**Comment by thaJeztah** [comment]
argh; looks like we broke the build because a PR was outdated https://ci.docker.com/public/blue/rest/organizations/jenkins/pipelines/moby/branches/PR-39808/runs/1/nodes/34/log/?start=0

```
2019-08-28T00:25:05.585Z] Building test suite binary /go/src/github.com/docker/docker/integration/build/test.main
[2019-08-28T00:27:12.031Z] # github.com/docker/docker/builder/dockerfile
[2019-08-28T00:27:12.031Z] builder/dockerfile/copy.go:566:29: too many arguments in call to system.MkdirAll
[2019-08-28T00:27:12.031Z] 	have (string, number, string)
[2019-08-28T00:27:12.031Z] 	want (string, os.FileMode)
[2019-08-28T00:27:12.288Z] # github.com/docker/docker/builder/dockerfile
[2019-08-28T00:27:12.288Z] builder/dockerfile/copy.go:566:29: too many arguments in call to system.MkdirAll
[2019-08-28T00:27:12.288Z] 	have (string, number, string)
[2019-08-28T00:27:12.288Z] 	want (string, os.FileMode)
[2019-08-28T00:27:12.288Z] # github.com/docker/docker/builder/dockerfile
[2019-08-28T00:27:12.288Z] builder/dockerfile/copy.go:566:29: too many arguments in call to system.MkdirAll
[2019-08-28T00:27:12.288Z] 	have (string, number, string)
[2019-08-28T00:27:12.288Z] 	want (string, os.FileMode
```

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/39809 to fix the build

**Review by tianon — APPROVED** [review]
Oops, heh; LGTM
