### PR TITLE
Improve default handling for "service create"

### LINKED ISSUE #24959: service create is using CLI defaults rather than leaving the fields empty
The CLI is creating a spec by doing something like:

``` go
    service = swarm.ServiceSpec{
        TaskTemplate: swarm.TaskSpec{
                        [...]
            Resources:     opts.resources.ToResourceRequirements(),
            RestartPolicy: opts.restartPolicy.ToRestartPolicy(),
            Placement: &swarm.Placement{
                Constraints: opts.constraints,
            },
        },
        Mode: swarm.ServiceMode{},
        UpdateConfig: &swarm.UpdateConfig{
            Parallelism: opts.update.parallelism,
            Delay:       opts.update.delay,
        },
        Networks:     convertNetworks(opts.networks),
        EndpointSpec: opts.endpoint.ToEndpointSpec(),
    }
```

This is pretty bad because it hardcodes the CLI defaults into the server. We have no way to make a distinction between a user **wanting** something versus a user leaving the defaults.

For example, the user runs a `docker service create foo`, no arguments.
Rather than leaving RestartPolicy to null, we're filling it up with stuff:

``` go
func (r *restartPolicyOptions) ToRestartPolicy() *swarm.RestartPolicy {
    return &swarm.RestartPolicy{
        Condition:   swarm.RestartPolicyCondition(r.condition),
        Delay:       r.delay.Value(),
        MaxAttempts: r.maxAttempts.Value(),
        Window:      r.window.Value(),
    }
}
```

We're incapable to know whether the user wanted something to be done about restart policies or if it's just the CLI setting defaults.

### LINKED ISSUE #32094: service update command should not have defaults
Stating default in `service update` command is misleading. If you don't specify a flag, it keeps its existing value. We should remove defaults in update command.

```
$ docker service update --help
...
      --update-delay duration              Delay between updates (ns|us|ms|s|m|h) (default 0s)
      --update-failure-action string       Action on update failure ("pause"|"continue"|"rollback") (default "pause")
      --update-monitor duration            Duration after each task update to monitor for failure (ns|us|ms|s|m|h)
      --update-parallelism uint            Maximum number of tasks updated simultaneously (0 to update all at once) (default 1)
```

cc @aaronlehmann.

### PR DESCRIPTION
**Pull request by aaronlehmann**
Currently, the CLI hardcodes several defaults. This is a problem because it's awkward to keep CLI defaults in sync with swarmkit defaults. Also, when a service is being created, it generally takes on several default values of flags that the user did not specify. If these defaults are changed later in swarmkit, they will not apply to those services, because they will continue to use whatever the CLI hardcoded at the time.

This PR makes two changes across two commits.

1) Changes `docker service inspect` to use the new `InsertDefaults` flag so that fields that are omitted in the service definition show default values in `docker service inspect`. This paves the way for `docker service create` to avoid hardcoding its defaults in services without hiding information from `inspect`.

2) Changes `docker service create` to omit fields that are not specified by the user, when possible. This will allow defaults to be applied inside the manager. To provide visibility into defaults in the CLI help, the CLI uses swarmkit's `api/defaults` package to annotate `docker service create --help` output. These defaults are left out of `docker service update --help`, because defaults are misleading in this context - if a flag is not specified, it has no default action.

Fixes #24959
Fixes #32094

ping @aluzzardi @dongluochen @dnephin @thaJeztah

### CODE REVIEW

**Comment by vieux** [comment]
ping @dnephin

File: cli/command/service/opts.go [hunk 1]
```diff
@@ -506,35 +586,122 @@ func addServiceFlags(flags *pflag.FlagSet, opts *serviceOptions) {
...
+	flags.Uint64Var(&opts.rollback.parallelism, flagRollbackParallelism, defaultRollbackParallelism, "Maximum number of tasks rolled back simultaneously (0 to roll back all at once)")
 	flags.SetAnnotation(flagRollbackParallelism, "version", []string{"1.28"})
-	flags.DurationVar(&opts.rollback.delay, flagRollbackDelay, time.Duration(0), "Delay between task rollbacks (ns|us|ms|s|m|h) (default 0s)")
+
+	rollbackDelayDesc := "Delay between task rollbacks (ns|us|ms|s|m|h)"
+	if !isUpdate {
+		defaultRollbackDelay := defaults.Service.Rollback.Delay
+		rollbackDelayDesc += fmt.Sprintf(" (default %s)", defaultRollbackDelay)
+	}
+	flags.DurationVar(&opts.rollback.delay, flagRollbackDelay, 0, rollbackDelayDesc)
```
Comment (dnephin) [inline cli/command/service/opts.go]: Why does the help string claim a default that isn't actually set as the default on the flag?

File: cli/command/service/opts.go [hunk 2]
```diff
@@ -469,33 +499,83 @@ func (opts *serviceOptions) ToService() (swarm.ServiceSpec, error) {
...
+		Networks:     convertNetworks(opts.networks.GetAll()),
+		Mode:         serviceMode,
+		EndpointSpec: opts.endpoint.ToEndpointSpec(),
 	}
 
+	if flags.Changed(flagStopGracePeriod) {
+		service.TaskTemplate.ContainerSpec.StopGracePeriod = opts.stopGrace.Value()
+	}
+	if anyChanged(flags, flagRestartDelay, flagRestartMaxAttempts, flagRestartWindow, flagRestartCondition) {
+		service.TaskTemplate.RestartPolicy = opts.restartPolicy.defaults()
```
Comment (dnephin) [inline cli/command/service/opts.go]: I would love to find a way to avoid needing `flags` here, but I can't find any right now.

Can we move this these back to the `ToRestartPolicy()` function, and add a `flags` arg ? (and the same with the few below this)

**Review by dnephin — COMMENTED** [review]
It's unfortunate that the `pflag` library tries to stay so close to the golang `flag` package API. It is not well suited for this type of behaviour.

File: client/service_inspect.go [hunk 3]
```diff
@@ -3,16 +3,20 @@ package client
...
+	"net/url"
 
 	"github.com/docker/docker/api/types/swarm"
 	"golang.org/x/net/context"
 )
 
 // ServiceInspectWithRaw returns the service information and the raw data.
-func (cli *Client) ServiceInspectWithRaw(ctx context.Context, serviceID string) (swarm.Service, []byte, error) {
-	serverResp, err := cli.get(ctx, "/services/"+serviceID, nil, nil)
+func (cli *Client) ServiceInspectWithRaw(ctx context.Context, serviceID string, insertDefaults bool) (swarm.Service, []byte, error) {
```
Comment (aaronlehmann) [inline client/service_inspect.go]: SGTM. I noticed that there was a mix of styles, with some functions taking `verbose`, or `force` boolean arguments. I can switch to an options structure if that's the preferred style.

File: cli/command/service/opts.go [hunk 4]
```diff
@@ -190,13 +196,15 @@ type updateOptions struct {
 	maxFailureRatio floatValue
 }
 
-func (opts updateOptions) config() *swarm.UpdateConfig {
+func (opts updateOptions) defaults(defaultUpdateConfig *api.UpdateConfig) *swarm.UpdateConfig {
```
Comment (aaronlehmann) [inline cli/command/service/opts.go]: This is passed either `defaults.Service.Update` or `defaults.Rollback.Update`. I agree that it's strange as a method on `updateOpts`. I'll change it to a function.

Any preference on whether it should be a single function that takes a `*api.UpdateConfig` (like this method), or separate functions that call a shared implementation with either the `Update` or `Rollback` default values?

File: cli/command/service/opts.go (hunk 1 above)
Comment (aaronlehmann) [inline cli/command/service/opts.go]: `DurationVar` is a little weird. IIRC it shows the default value in the CLI help, but only if it's nonzero. I'd like us to always show the default on `service create`, even if it's zero, and never show it on `service update`. So it made sense to manipulate the flag description instead of providing a default value. If we did both, the default value would appear twice when the default is nonzero.

I can add a comment explaing this.

File: cli/command/service/opts.go (hunk 4 above)
Comment (dnephin) [inline cli/command/service/opts.go]: Ah, I missed that, thanks!

This method moved to a function as-is sgtm.

**Comment by aaronlehmann** [comment]
@dnephin: Thanks for the thoughtful review. I've addressed the comments - PTAL

**Comment by aaronlehmann** [comment]
Rebased

**Comment by thaJeztah** [comment]
I like this, finally time to give it a quick look (from a UX perspective), and seeing actual defaults in `docker service create --help` is really cool.

I haven't had time yet to test against an _actually_ older daemon, but running this;

    DOCKER_API_VERSION=1.26 docker service create --help

Seems to still show the defaults in `docker service create --help`; is that expected?

**Comment by aaronlehmann** [comment]
> I haven't had time yet to test against an _actually_ older daemon, but running this;
> 
>     DOCKER_API_VERSION=1.26 docker service create --help
> 
> Seems to still show the defaults in `docker service create --help`; is that expected?

Yes, it's expected. I've pondered the idea of adding an API endpoint where the client can query what defaults are in place on the manager. But it seems like a lot of complexity for something that is generally not a factor (defaults change rarely, and mixed client/server version setups are unusual, and the worst case outcome is outdated help text). In this implementation, the defaults shown in CLI help are linked into the client at build time.

If you think fetching the defaults via an API is worth it, we could consider going in that direction.

**Comment by aaronlehmann** [comment]
Rebased

**Review by dnephin — COMMENTED** [review]
Design LGTM

**Comment by aaronlehmann** [comment]
Rebased

File: docs/reference/commandline/service_update.md [hunk 5]
```diff
@@ -21,74 +21,73 @@ Usage:  docker service update [OPTIONS] SERVICE
...
       --force                              Force update even if no changes require it
-      --group-add list                     Add an additional supplementary user group to the container (default [])
-      --group-rm list                      Remove a previously added supplementary user group from the container (default [])
+      --group-add list                     Add an additional supplementary user group to the container
+      --group-rm list                      Remove a previously added supplementary user group from the container
       --health-cmd string                  Command to run to check health
       --health-interval duration           Time between running the check (ns|us|ms|s|m|h)
       --health-retries int                 Consecutive failures needed to report unhealthy
       --health-timeout duration            Maximum time to allow one check to run (ns|us|ms|s|m|h)
       --health-start-period duration       Start period for the container to initialize before counting retries towards unstable (ns|us|ms|s|m|h) (default 0s)
```
Comment (dongluochen) [inline docs/reference/commandline/service_update.md]: remove `(default 0s)`

**Review by dongluochen — COMMENTED** [review]
sgtm

File: docs/reference/commandline/service_update.md (hunk 5 above)
Comment (aaronlehmann) [inline docs/reference/commandline/service_update.md]: Fixed

**Comment by dongluochen** [comment]
design lgtm.

**Review by vdemeester — COMMENTED** [review]
Design LGTM, moving to code review

**Comment by vdemeester** [comment]
@aaronlehmann needs a rebase 👼

**Comment by aaronlehmann** [comment]
Rebased. `flagUpdateOrder` and `flagRollbackOrder` are now handled.

**Comment by vieux** [comment]
@aaronlehmann seems like the windows failure is related
`..\..\api\server\router\swarm\helpers.go:42: not enough arguments in call to sr.backend.GetService`

**Comment by aaronlehmann** [comment]
@vieux: Looks like the Windows build was broken by #32154. It's not related to this change.

**Comment by aaronlehmann** [comment]
Deleted my earlier comment, because it was indeed a problem with this PR. I thought it was an existing problem on master, but it turned out the reason it only showed up on windows was because each builder does a separate merge to master so they're not building the same version of the code (which is kind of a problem IMHO!).

**Comment by aaronlehmann** [comment]
@vieux: Fixed, thanks!

**Review by vdemeester — APPROVED** [review]
LGTM 🐯

**Comment by thaJeztah** [comment]
I'm a bit confused, but probably do something wrong..

```bash
docker service create --restart-condition="on-failure" --name web nginx:alpine
2i3pres421je9kuo5rh1vf2n4
```

Makes this request;

```json
{
  "EndpointSpec": {
    "Mode": "vip"
  },
  "Labels": {},
  "Mode": {
    "Replicated": {}
  },
  "Name": "web",
  "TaskTemplate": {
    "ContainerSpec": {
      "DNSConfig": {},
      "Image": "nginx:alpine"
    },
    "ForceUpdate": 0,
    "Placement": {},
    "Resources": {
      "Limits": {},
      "Reservations": {}
    },
    "RestartPolicy": {
      "Condition": "on-failure",
      "Delay": 5000000000,
      "MaxAttempts": 0
    }
  }
}
````


With the `insertDefaults=true` option set;

```bash
/ # curl --unix-socket /var/run/docker.sock -sL http://localhost/v1.29/services/web?insertDefaults=true | jq .
{
  "ID": "2i3pres421je9kuo5rh1vf2n4",
  "Version": {
    "Index": 31
  },
  "CreatedAt": "2017-04-10T09:36:58.859857088Z",
  "UpdatedAt": "2017-04-10T09:36:58.859857088Z",
  "Spec": {
    "Name": "web",
    "Labels": {},
    "TaskTemplate": {
      "ContainerSpec": {
        "Image": "nginx:alpine@sha256:5aadb68304a38a8e2719605e4e180413f390cd6647602bee9bdedd59753c3590",
        "DNSConfig": {}
      },
      "Resources": {
        "Limits": {},
        "Reservations": {}
      },
      "RestartPolicy": {
        "Condition": "on-failure",
        "Delay": 5000000000,
        "MaxAttempts": 0
      },
      "Placement": {},
      "ForceUpdate": 0
    },
    "Mode": {
      "Replicated": {
        "Replicas": 1
      }
    },
    "EndpointSpec": {
      "Mode": "vip"
    }
  },
  "Endpoint": {
    "Spec": {}
  }
}
```

Without the `insertDefaults=true` option set;

```bash
/ # curl --unix-socket /var/run/docker.sock -sL http://localhost/v1.29/services/web | jq .
{
  "ID": "2i3pres421je9kuo5rh1vf2n4",
  "Version": {
    "Index": 31
  },
  "CreatedAt": "2017-04-10T09:36:58.859857088Z",
  "UpdatedAt": "2017-04-10T09:36:58.859857088Z",
  "Spec": {
    "Name": "web",
    "Labels": {},
    "TaskTemplate": {
      "ContainerSpec": {
        "Image": "nginx:alpine@sha256:5aadb68304a38a8e2719605e4e180413f390cd6647602bee9bdedd59753c3590",
        "DNSConfig": {}
      },
      "Resources": {
        "Limits": {},
        "Reservations": {}
      },
      "RestartPolicy": {
        "Condition": "on-failure",
        "Delay": 5000000000,
        "MaxAttempts": 0
      },
      "Placement": {},
      "ForceUpdate": 0
    },
    "Mode": {
      "Replicated": {
        "Replicas": 1
      }
    },
    "EndpointSpec": {
      "Mode": "vip"
    }
  },
  "Endpoint": {
    "Spec": {}
  }
}
```

**Comment by aaronlehmann** [comment]
@thaJeztah: You're right - there was a problem. Specifying the service ID led to the correct behavior, but services names were not handled properly, as the service was returned directly from `ListServices`. I've fixed this and added test coverage.

**Comment by thaJeztah** [comment]
Ah! That looks better;

```bash
docker service inspect web
[
    {
        "ID": "k850seipz5ohpemq1cotenze2",
        "Version": {
            "Index": 10
        },
        "CreatedAt": "2017-04-11T10:51:21.181483381Z",
        "UpdatedAt": "2017-04-11T10:51:21.181483381Z",
        "Spec": {
            "Name": "web",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "nginx:alpine@sha256:5aadb68304a38a8e2719605e4e180413f390cd6647602bee9bdedd59753c3590",
                    "StopGracePeriod": 10000000000,
                    "DNSConfig": {}
                },
                "Resources": {
                    "Limits": {},
                    "Reservations": {}
                },
                "RestartPolicy": {
                    "Condition": "on-failure",
                    "Delay": 5000000000,
                    "MaxAttempts": 0
                },
                "Placement": {},
                "ForceUpdate": 0
            },
            "Mode": {
                "Replicated": {
                    "Replicas": 1
                }
            },
            "UpdateConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "RollbackConfig": {
                "Parallelism": 1,
                "FailureAction": "pause",
                "Monitor": 5000000000,
                "MaxFailureRatio": 0,
                "Order": "stop-first"
            },
            "EndpointSpec": {
                "Mode": "vip"
            }
        },
        "Endpoint": {
            "Spec": {}
        }
    }
]
```

File: api/swagger.yaml [hunk 6]
```diff
@@ -7584,6 +7584,11 @@ paths:
           description: "ID or name of service."
           required: true
           type: "string"
+        - name: "insertDefaults"
```
Comment (thaJeztah) [inline api/swagger.yaml]: This needs to be added to the API version-history; https://github.com/docker/docker/blob/master/docs/api/version-history.md

(ok with doing that in a follow-up)

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
All green; I'll go ahead and merge so that this is in 17.05. I'll include the API version changes https://github.com/docker/docker/pull/32284#discussion_r110872635 in the "changelog" pull request
